run:
  tests: true
  timeout: 10m
service:
  golangci-lint-version: 1.32.2
linters:
  enable-all: true
  disable:
    - gomnd
    - godot
    - wrapcheck
    - funlen
    - lll
    - gci
linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  golint:
    min-confidence: 0
  maligned:
    suggest-new: true
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
    disabled-checks:
      - wrapperFunc
      - dupImport # https://github.com/go-critic/go-critic/issues/845
